### ISSUE TITLE
Pick a testing framework

### ISSUE THREAD

**Issue by myw** [myw/sehrvy#3]
It seems like, for our simple purposes, `Test::Simple` and `Test::More` will do the trick. I propose making `t/Foo.t` files for every module we need, and maybe the scripts, too. They can then be run with the `prove` command from the directory with the module files. An individual `.t` file can `use` whichever testing module it needs to. 

Although this structure is not explicitly enforced by the testing framework, we should try to make tests not too interdependent. And we should comment what every test is doing at the start of the testing block, for example:

``` perl
# Check equality of exponentiation
my $foo = 3*3;
my $bar = 3**2;
ok($foo == $bar, 'exponentiation works');
```

Thoughts?

**Comment by ezimanyi** [comment]
I think that `Test::Simple` and `Test::More` will work fine for what we need to do.  I'll modify my `test_db.t` script and make sure I can get `prove` working on it.

**Comment by myw** [comment]
Since we've settled on this, I'm closing the issue.
